name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: Aquillae777/github-profile-3d-contrib@0.7.0
        env:
          GITHUB_TOKEN:  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 
          USERNAME:  Aquillae777 
      - name: Commit & Push
        run: |
          git config user.name Aquillae777
          git config user.email Aquillae777@gmail.com
          git add -A .
          git commit -m "generated"
          git push
